// Generated by CoffeeScript 2.5.1
(function() {
  var getChars, main;

  getChars = function(charString) {
    var ran;
    ran = +(Math.random() * (charString.length - 1) + 0).toFixed(0);
    return charString[ran];
  };

  main = function() {
    var capitals, combined, i, len, lowercase, numbers, password, specials;
    len = 10;
    i = 0;
    capitals = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    lowercase = 'abcdefghijklmnopqrstuvwxyz';
    numbers = '0123456789';
    specials = '~!"#$%&()*+,-./:;<=>?@';
    combined = capitals.concat(lowercase, numbers, specials);
    password = '';
    while (i < 10) {
      password += (function() {
        switch (i) {
          case 0:
          case 1:
            return getChars(capitals);
          case 2:
          case 3:
            return getChars(lowercase);
          case 4:
          case 5:
            return getChars(numbers);
          case 6:
          case 7:
            return getChars(specials);
          default:
            return getChars(combined);
        }
      })();
      i++;
    }
    return console.log(password);
  };

  main();

}).call(this);
